### PR TITLE
Added support for SINGLE separator in scroller mode. run jirafe.html …

### PR DESCRIPTION
**Pull request by AndriyIvaskevych**
What?
Added support for decimal point 
NOTE that tick.js file is auto-generated
Why?
decimal value were not supported  by plugin

How to test?
Use the code from:
https://github.com/AndriyIvaskevych/tick/tree/fix_for_separator_in_Scroller
find and run \demo\jirafe.html

ping @bc-jirafe/edvantis

### CODE REVIEW

**Comment by victor-ivanov** [comment]
:+1:

**Comment by roman-drebotiy** [comment]
:+1:

**Comment by AndriyIvaskevych** [comment]
agree, that is a reason, This verification was added to skip error when some issue with update but coffee script generates not expected JS code

**Comment by roman-drebotiy** [comment]
:+1:

**Pull request merged**
